#!/usr/bin/env python3
"""
Static Ticker Database

Comprehensive static database of major NYSE and NASDAQ tickers.
Used as fallback when external APIs are unavailable.
"""

def get_comprehensive_ticker_database():
    """Return a comprehensive database of major stock tickers."""
    return [
        # Technology Sector
        {'symbol': 'AAPL', 'name': 'Apple Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Consumer Electronics'},
        {'symbol': 'MSFT', 'name': 'Microsoft Corporation', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'GOOGL', 'name': 'Alphabet Inc. Class A', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Internet'},
        {'symbol': 'GOOG', 'name': 'Alphabet Inc. Class C', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Internet'},
        {'symbol': 'AMZN', 'name': 'Amazon.com Inc.', 'exchange': 'NASDAQ', 'sector': 'Consumer Discretionary', 'industry': 'E-commerce'},
        {'symbol': 'META', 'name': 'Meta Platforms Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Social Media'},
        {'symbol': 'NVDA', 'name': 'NVIDIA Corporation', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Semiconductors'},
        {'symbol': 'TSLA', 'name': 'Tesla Inc.', 'exchange': 'NASDAQ', 'sector': 'Consumer Discretionary', 'industry': 'Electric Vehicles'},
        {'symbol': 'NFLX', 'name': 'Netflix Inc.', 'exchange': 'NASDAQ', 'sector': 'Communication Services', 'industry': 'Streaming'},
        {'symbol': 'ADBE', 'name': 'Adobe Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'CRM', 'name': 'Salesforce Inc.', 'exchange': 'NYSE', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'ORCL', 'name': 'Oracle Corporation', 'exchange': 'NYSE', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'INTC', 'name': 'Intel Corporation', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Semiconductors'},
        {'symbol': 'AMD', 'name': 'Advanced Micro Devices Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Semiconductors'},
        {'symbol': 'QCOM', 'name': 'QUALCOMM Incorporated', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Semiconductors'},
        {'symbol': 'TXN', 'name': 'Texas Instruments Incorporated', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Semiconductors'},
        {'symbol': 'AVGO', 'name': 'Broadcom Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Semiconductors'},
        {'symbol': 'CSCO', 'name': 'Cisco Systems Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Networking'},
        {'symbol': 'IBM', 'name': 'International Business Machines Corporation', 'exchange': 'NYSE', 'sector': 'Technology', 'industry': 'IT Services'},
        {'symbol': 'NOW', 'name': 'ServiceNow Inc.', 'exchange': 'NYSE', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'SNOW', 'name': 'Snowflake Inc.', 'exchange': 'NYSE', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'ZM', 'name': 'Zoom Video Communications Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'DOCU', 'name': 'DocuSign Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'CRWD', 'name': 'CrowdStrike Holdings Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Cybersecurity'},
        {'symbol': 'OKTA', 'name': 'Okta Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Cybersecurity'},
        {'symbol': 'PANW', 'name': 'Palo Alto Networks Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Cybersecurity'},
        {'symbol': 'NET', 'name': 'Cloudflare Inc.', 'exchange': 'NYSE', 'sector': 'Technology', 'industry': 'Internet Infrastructure'},
        {'symbol': 'DDOG', 'name': 'Datadog Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'MDB', 'name': 'MongoDB Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'TEAM', 'name': 'Atlassian Corporation', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        
        # Financial Sector
        {'symbol': 'JPM', 'name': 'JPMorgan Chase & Co.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'BAC', 'name': 'Bank of America Corp.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'WFC', 'name': 'Wells Fargo & Company', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'GS', 'name': 'Goldman Sachs Group Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Investment Banking'},
        {'symbol': 'MS', 'name': 'Morgan Stanley', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Investment Banking'},
        {'symbol': 'C', 'name': 'Citigroup Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'AXP', 'name': 'American Express Company', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Credit Services'},
        {'symbol': 'V', 'name': 'Visa Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Payment Processing'},
        {'symbol': 'MA', 'name': 'Mastercard Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Payment Processing'},
        {'symbol': 'PYPL', 'name': 'PayPal Holdings Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Payment Processing'},
        {'symbol': 'SQ', 'name': 'Block Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Payment Processing'},
        {'symbol': 'COIN', 'name': 'Coinbase Global Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Cryptocurrency'},
        {'symbol': 'SOFI', 'name': 'SoFi Technologies Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Fintech'},
        {'symbol': 'UPST', 'name': 'Upstart Holdings Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Fintech'},
        {'symbol': 'HOOD', 'name': 'Robinhood Markets Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Trading'},
        {'symbol': 'SCHW', 'name': 'Charles Schwab Corporation', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Investment Services'},
        {'symbol': 'BLK', 'name': 'BlackRock Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Asset Management'},
        {'symbol': 'BX', 'name': 'Blackstone Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Private Equity'},
        {'symbol': 'KKR', 'name': 'KKR & Co. Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Private Equity'},
        
        # Healthcare Sector
        {'symbol': 'JNJ', 'name': 'Johnson & Johnson', 'exchange': 'NYSE', 'sector': 'Healthcare', 'industry': 'Pharmaceuticals'},
        {'symbol': 'PFE', 'name': 'Pfizer Inc.', 'exchange': 'NYSE', 'sector': 'Healthcare', 'industry': 'Pharmaceuticals'},
        {'symbol': 'UNH', 'name': 'UnitedHealth Group Inc.', 'exchange': 'NYSE', 'sector': 'Healthcare', 'industry': 'Health Insurance'},
        {'symbol': 'ABBV', 'name': 'AbbVie Inc.', 'exchange': 'NYSE', 'sector': 'Healthcare', 'industry': 'Pharmaceuticals'},
        {'symbol': 'MRK', 'name': 'Merck & Co. Inc.', 'exchange': 'NYSE', 'sector': 'Healthcare', 'industry': 'Pharmaceuticals'},
        {'symbol': 'TMO', 'name': 'Thermo Fisher Scientific Inc.', 'exchange': 'NYSE', 'sector': 'Healthcare', 'industry': 'Life Sciences'},
        {'symbol': 'ABT', 'name': 'Abbott Laboratories', 'exchange': 'NYSE', 'sector': 'Healthcare', 'industry': 'Medical Devices'},
        {'symbol': 'DHR', 'name': 'Danaher Corporation', 'exchange': 'NYSE', 'sector': 'Healthcare', 'industry': 'Life Sciences'},
        {'symbol': 'BMY', 'name': 'Bristol Myers Squibb Company', 'exchange': 'NYSE', 'sector': 'Healthcare', 'industry': 'Pharmaceuticals'},
        {'symbol': 'AMGN', 'name': 'Amgen Inc.', 'exchange': 'NASDAQ', 'sector': 'Healthcare', 'industry': 'Biotechnology'},
        {'symbol': 'GILD', 'name': 'Gilead Sciences Inc.', 'exchange': 'NASDAQ', 'sector': 'Healthcare', 'industry': 'Biotechnology'},
        {'symbol': 'BIIB', 'name': 'Biogen Inc.', 'exchange': 'NASDAQ', 'sector': 'Healthcare', 'industry': 'Biotechnology'},
        {'symbol': 'REGN', 'name': 'Regeneron Pharmaceuticals Inc.', 'exchange': 'NASDAQ', 'sector': 'Healthcare', 'industry': 'Biotechnology'},
        {'symbol': 'VRTX', 'name': 'Vertex Pharmaceuticals Incorporated', 'exchange': 'NASDAQ', 'sector': 'Healthcare', 'industry': 'Biotechnology'},
        {'symbol': 'ILMN', 'name': 'Illumina Inc.', 'exchange': 'NASDAQ', 'sector': 'Healthcare', 'industry': 'Life Sciences'},
        {'symbol': 'ISRG', 'name': 'Intuitive Surgical Inc.', 'exchange': 'NASDAQ', 'sector': 'Healthcare', 'industry': 'Medical Devices'},
        {'symbol': 'MDT', 'name': 'Medtronic plc', 'exchange': 'NYSE', 'sector': 'Healthcare', 'industry': 'Medical Devices'},
        {'symbol': 'SYK', 'name': 'Stryker Corporation', 'exchange': 'NYSE', 'sector': 'Healthcare', 'industry': 'Medical Devices'},
        {'symbol': 'BSX', 'name': 'Boston Scientific Corporation', 'exchange': 'NYSE', 'sector': 'Healthcare', 'industry': 'Medical Devices'},
        {'symbol': 'ZTS', 'name': 'Zoetis Inc.', 'exchange': 'NYSE', 'sector': 'Healthcare', 'industry': 'Animal Health'},
        
        # Consumer Staples
        {'symbol': 'PG', 'name': 'Procter & Gamble Co.', 'exchange': 'NYSE', 'sector': 'Consumer Staples', 'industry': 'Household Products'},
        {'symbol': 'KO', 'name': 'Coca-Cola Company', 'exchange': 'NYSE', 'sector': 'Consumer Staples', 'industry': 'Beverages'},
        {'symbol': 'PEP', 'name': 'PepsiCo Inc.', 'exchange': 'NASDAQ', 'sector': 'Consumer Staples', 'industry': 'Beverages'},
        {'symbol': 'WMT', 'name': 'Walmart Inc.', 'exchange': 'NYSE', 'sector': 'Consumer Staples', 'industry': 'Retail'},
        {'symbol': 'COST', 'name': 'Costco Wholesale Corporation', 'exchange': 'NASDAQ', 'sector': 'Consumer Staples', 'industry': 'Retail'},
        {'symbol': 'TGT', 'name': 'Target Corporation', 'exchange': 'NYSE', 'sector': 'Consumer Staples', 'industry': 'Retail'},
        {'symbol': 'CL', 'name': 'Colgate-Palmolive Company', 'exchange': 'NYSE', 'sector': 'Consumer Staples', 'industry': 'Household Products'},
        {'symbol': 'KMB', 'name': 'Kimberly-Clark Corporation', 'exchange': 'NYSE', 'sector': 'Consumer Staples', 'industry': 'Household Products'},
        {'symbol': 'GIS', 'name': 'General Mills Inc.', 'exchange': 'NYSE', 'sector': 'Consumer Staples', 'industry': 'Food Products'},
        {'symbol': 'K', 'name': 'Kellogg Company', 'exchange': 'NYSE', 'sector': 'Consumer Staples', 'industry': 'Food Products'},
        {'symbol': 'HSY', 'name': 'The Hershey Company', 'exchange': 'NYSE', 'sector': 'Consumer Staples', 'industry': 'Food Products'},
        {'symbol': 'MKC', 'name': 'McCormick & Company Incorporated', 'exchange': 'NYSE', 'sector': 'Consumer Staples', 'industry': 'Food Products'},
        
        # Consumer Discretionary
        {'symbol': 'HD', 'name': 'Home Depot Inc.', 'exchange': 'NYSE', 'sector': 'Consumer Discretionary', 'industry': 'Retail'},
        {'symbol': 'MCD', 'name': 'McDonald\'s Corporation', 'exchange': 'NYSE', 'sector': 'Consumer Discretionary', 'industry': 'Restaurants'},
        {'symbol': 'NKE', 'name': 'Nike Inc.', 'exchange': 'NYSE', 'sector': 'Consumer Discretionary', 'industry': 'Apparel'},
        {'symbol': 'DIS', 'name': 'Walt Disney Company', 'exchange': 'NYSE', 'sector': 'Communication Services', 'industry': 'Entertainment'},
        {'symbol': 'SBUX', 'name': 'Starbucks Corporation', 'exchange': 'NASDAQ', 'sector': 'Consumer Discretionary', 'industry': 'Restaurants'},
        {'symbol': 'LOW', 'name': 'Lowe\'s Companies Inc.', 'exchange': 'NYSE', 'sector': 'Consumer Discretionary', 'industry': 'Retail'},
        {'symbol': 'TJX', 'name': 'The TJX Companies Inc.', 'exchange': 'NYSE', 'sector': 'Consumer Discretionary', 'industry': 'Retail'},
        {'symbol': 'BKNG', 'name': 'Booking Holdings Inc.', 'exchange': 'NASDAQ', 'sector': 'Consumer Discretionary', 'industry': 'Travel'},
        {'symbol': 'EXPE', 'name': 'Expedia Group Inc.', 'exchange': 'NASDAQ', 'sector': 'Consumer Discretionary', 'industry': 'Travel'},
        {'symbol': 'ABNB', 'name': 'Airbnb Inc.', 'exchange': 'NASDAQ', 'sector': 'Consumer Discretionary', 'industry': 'Travel'},
        {'symbol': 'UBER', 'name': 'Uber Technologies Inc.', 'exchange': 'NYSE', 'sector': 'Consumer Discretionary', 'industry': 'Transportation'},
        {'symbol': 'LYFT', 'name': 'Lyft Inc.', 'exchange': 'NASDAQ', 'sector': 'Consumer Discretionary', 'industry': 'Transportation'},
        {'symbol': 'DASH', 'name': 'DoorDash Inc.', 'exchange': 'NYSE', 'sector': 'Consumer Discretionary', 'industry': 'Food Delivery'},
        {'symbol': 'ROKU', 'name': 'Roku Inc.', 'exchange': 'NASDAQ', 'sector': 'Consumer Discretionary', 'industry': 'Entertainment'},
        {'symbol': 'PTON', 'name': 'Peloton Interactive Inc.', 'exchange': 'NASDAQ', 'sector': 'Consumer Discretionary', 'industry': 'Fitness'},
        
        # Industrials
        {'symbol': 'BA', 'name': 'Boeing Company', 'exchange': 'NYSE', 'sector': 'Industrials', 'industry': 'Aerospace'},
        {'symbol': 'CAT', 'name': 'Caterpillar Inc.', 'exchange': 'NYSE', 'sector': 'Industrials', 'industry': 'Heavy Machinery'},
        {'symbol': 'GE', 'name': 'General Electric Company', 'exchange': 'NYSE', 'sector': 'Industrials', 'industry': 'Conglomerate'},
        {'symbol': 'HON', 'name': 'Honeywell International Inc.', 'exchange': 'NASDAQ', 'sector': 'Industrials', 'industry': 'Conglomerate'},
        {'symbol': 'UPS', 'name': 'United Parcel Service Inc.', 'exchange': 'NYSE', 'sector': 'Industrials', 'industry': 'Logistics'},
        {'symbol': 'FDX', 'name': 'FedEx Corporation', 'exchange': 'NYSE', 'sector': 'Industrials', 'industry': 'Logistics'},
        {'symbol': 'LMT', 'name': 'Lockheed Martin Corporation', 'exchange': 'NYSE', 'sector': 'Industrials', 'industry': 'Defense'},
        {'symbol': 'RTX', 'name': 'Raytheon Technologies Corporation', 'exchange': 'NYSE', 'sector': 'Industrials', 'industry': 'Defense'},
        {'symbol': 'MMM', 'name': '3M Company', 'exchange': 'NYSE', 'sector': 'Industrials', 'industry': 'Conglomerate'},
        {'symbol': 'DE', 'name': 'Deere & Company', 'exchange': 'NYSE', 'sector': 'Industrials', 'industry': 'Heavy Machinery'},
        {'symbol': 'EMR', 'name': 'Emerson Electric Co.', 'exchange': 'NYSE', 'sector': 'Industrials', 'industry': 'Electrical Equipment'},
        {'symbol': 'ETN', 'name': 'Eaton Corporation plc', 'exchange': 'NYSE', 'sector': 'Industrials', 'industry': 'Electrical Equipment'},
        {'symbol': 'ITW', 'name': 'Illinois Tool Works Inc.', 'exchange': 'NYSE', 'sector': 'Industrials', 'industry': 'Manufacturing'},
        {'symbol': 'PH', 'name': 'Parker-Hannifin Corporation', 'exchange': 'NYSE', 'sector': 'Industrials', 'industry': 'Manufacturing'},
        {'symbol': 'CMI', 'name': 'Cummins Inc.', 'exchange': 'NYSE', 'sector': 'Industrials', 'industry': 'Engines'},
        
        # Energy
        {'symbol': 'XOM', 'name': 'Exxon Mobil Corporation', 'exchange': 'NYSE', 'sector': 'Energy', 'industry': 'Oil & Gas'},
        {'symbol': 'CVX', 'name': 'Chevron Corporation', 'exchange': 'NYSE', 'sector': 'Energy', 'industry': 'Oil & Gas'},
        {'symbol': 'COP', 'name': 'ConocoPhillips', 'exchange': 'NYSE', 'sector': 'Energy', 'industry': 'Oil & Gas'},
        {'symbol': 'EOG', 'name': 'EOG Resources Inc.', 'exchange': 'NYSE', 'sector': 'Energy', 'industry': 'Oil & Gas'},
        {'symbol': 'SLB', 'name': 'Schlumberger Limited', 'exchange': 'NYSE', 'sector': 'Energy', 'industry': 'Oil Services'},
        {'symbol': 'KMI', 'name': 'Kinder Morgan Inc.', 'exchange': 'NYSE', 'sector': 'Energy', 'industry': 'Pipeline'},
        {'symbol': 'PSX', 'name': 'Phillips 66', 'exchange': 'NYSE', 'sector': 'Energy', 'industry': 'Refining'},
        {'symbol': 'VLO', 'name': 'Valero Energy Corporation', 'exchange': 'NYSE', 'sector': 'Energy', 'industry': 'Refining'},
        {'symbol': 'MPC', 'name': 'Marathon Petroleum Corporation', 'exchange': 'NYSE', 'sector': 'Energy', 'industry': 'Refining'},
        {'symbol': 'OXY', 'name': 'Occidental Petroleum Corporation', 'exchange': 'NYSE', 'sector': 'Energy', 'industry': 'Oil & Gas'},
        {'symbol': 'PXD', 'name': 'Pioneer Natural Resources Company', 'exchange': 'NYSE', 'sector': 'Energy', 'industry': 'Oil & Gas'},
        {'symbol': 'DVN', 'name': 'Devon Energy Corporation', 'exchange': 'NYSE', 'sector': 'Energy', 'industry': 'Oil & Gas'},
        {'symbol': 'HES', 'name': 'Hess Corporation', 'exchange': 'NYSE', 'sector': 'Energy', 'industry': 'Oil & Gas'},
        {'symbol': 'MRO', 'name': 'Marathon Oil Corporation', 'exchange': 'NYSE', 'sector': 'Energy', 'industry': 'Oil & Gas'},
        {'symbol': 'FANG', 'name': 'Diamondback Energy Inc.', 'exchange': 'NASDAQ', 'sector': 'Energy', 'industry': 'Oil & Gas'},
        
        # Utilities
        {'symbol': 'NEE', 'name': 'NextEra Energy Inc.', 'exchange': 'NYSE', 'sector': 'Utilities', 'industry': 'Electric Utilities'},
        {'symbol': 'SO', 'name': 'Southern Company', 'exchange': 'NYSE', 'sector': 'Utilities', 'industry': 'Electric Utilities'},
        {'symbol': 'DUK', 'name': 'Duke Energy Corporation', 'exchange': 'NYSE', 'sector': 'Utilities', 'industry': 'Electric Utilities'},
        {'symbol': 'AEP', 'name': 'American Electric Power Company Inc.', 'exchange': 'NYSE', 'sector': 'Utilities', 'industry': 'Electric Utilities'},
        {'symbol': 'EXC', 'name': 'Exelon Corporation', 'exchange': 'NASDAQ', 'sector': 'Utilities', 'industry': 'Electric Utilities'},
        {'symbol': 'SRE', 'name': 'Sempra Energy', 'exchange': 'NYSE', 'sector': 'Utilities', 'industry': 'Gas Utilities'},
        {'symbol': 'XEL', 'name': 'Xcel Energy Inc.', 'exchange': 'NASDAQ', 'sector': 'Utilities', 'industry': 'Electric Utilities'},
        {'symbol': 'WEC', 'name': 'WEC Energy Group Inc.', 'exchange': 'NYSE', 'sector': 'Utilities', 'industry': 'Electric Utilities'},
        {'symbol': 'ES', 'name': 'Eversource Energy', 'exchange': 'NYSE', 'sector': 'Utilities', 'industry': 'Electric Utilities'},
        {'symbol': 'PEG', 'name': 'Public Service Enterprise Group Incorporated', 'exchange': 'NYSE', 'sector': 'Utilities', 'industry': 'Electric Utilities'},
        {'symbol': 'AWK', 'name': 'American Water Works Company Inc.', 'exchange': 'NYSE', 'sector': 'Utilities', 'industry': 'Water Utilities'},
        {'symbol': 'CNP', 'name': 'CenterPoint Energy Inc.', 'exchange': 'NYSE', 'sector': 'Utilities', 'industry': 'Electric Utilities'},
        {'symbol': 'ED', 'name': 'Consolidated Edison Inc.', 'exchange': 'NYSE', 'sector': 'Utilities', 'industry': 'Electric Utilities'},
        {'symbol': 'EIX', 'name': 'Edison International', 'exchange': 'NYSE', 'sector': 'Utilities', 'industry': 'Electric Utilities'},
        {'symbol': 'FE', 'name': 'FirstEnergy Corp.', 'exchange': 'NYSE', 'sector': 'Utilities', 'industry': 'Electric Utilities'},
        
        # Real Estate
        {'symbol': 'AMT', 'name': 'American Tower Corporation', 'exchange': 'NYSE', 'sector': 'Real Estate', 'industry': 'REITs'},
        {'symbol': 'PLD', 'name': 'Prologis Inc.', 'exchange': 'NYSE', 'sector': 'Real Estate', 'industry': 'REITs'},
        {'symbol': 'CCI', 'name': 'Crown Castle Inc.', 'exchange': 'NYSE', 'sector': 'Real Estate', 'industry': 'REITs'},
        {'symbol': 'EQIX', 'name': 'Equinix Inc.', 'exchange': 'NASDAQ', 'sector': 'Real Estate', 'industry': 'REITs'},
        {'symbol': 'PSA', 'name': 'Public Storage', 'exchange': 'NYSE', 'sector': 'Real Estate', 'industry': 'REITs'},
        {'symbol': 'EXR', 'name': 'Extra Space Storage Inc.', 'exchange': 'NYSE', 'sector': 'Real Estate', 'industry': 'REITs'},
        {'symbol': 'AVB', 'name': 'AvalonBay Communities Inc.', 'exchange': 'NYSE', 'sector': 'Real Estate', 'industry': 'REITs'},
        {'symbol': 'EQR', 'name': 'Equity Residential', 'exchange': 'NYSE', 'sector': 'Real Estate', 'industry': 'REITs'},
        {'symbol': 'MAA', 'name': 'Mid-America Apartment Communities Inc.', 'exchange': 'NYSE', 'sector': 'Real Estate', 'industry': 'REITs'},
        {'symbol': 'UDR', 'name': 'UDR Inc.', 'exchange': 'NYSE', 'sector': 'Real Estate', 'industry': 'REITs'},
        {'symbol': 'BXP', 'name': 'Boston Properties Inc.', 'exchange': 'NYSE', 'sector': 'Real Estate', 'industry': 'REITs'},
        {'symbol': 'KIM', 'name': 'Kimco Realty Corporation', 'exchange': 'NYSE', 'sector': 'Real Estate', 'industry': 'REITs'},
        {'symbol': 'REG', 'name': 'Regency Centers Corporation', 'exchange': 'NASDAQ', 'sector': 'Real Estate', 'industry': 'REITs'},
        {'symbol': 'SPG', 'name': 'Simon Property Group Inc.', 'exchange': 'NYSE', 'sector': 'Real Estate', 'industry': 'REITs'},
        {'symbol': 'MAC', 'name': 'Macerich Company', 'exchange': 'NYSE', 'sector': 'Real Estate', 'industry': 'REITs'},
        
        # Communication Services
        {'symbol': 'VZ', 'name': 'Verizon Communications Inc.', 'exchange': 'NYSE', 'sector': 'Communication Services', 'industry': 'Telecommunications'},
        {'symbol': 'T', 'name': 'AT&T Inc.', 'exchange': 'NYSE', 'sector': 'Communication Services', 'industry': 'Telecommunications'},
        {'symbol': 'CMCSA', 'name': 'Comcast Corporation', 'exchange': 'NASDAQ', 'sector': 'Communication Services', 'industry': 'Cable'},
        {'symbol': 'CHTR', 'name': 'Charter Communications Inc.', 'exchange': 'NASDAQ', 'sector': 'Communication Services', 'industry': 'Cable'},
        {'symbol': 'TMUS', 'name': 'T-Mobile US Inc.', 'exchange': 'NASDAQ', 'sector': 'Communication Services', 'industry': 'Telecommunications'},
        {'symbol': 'DISH', 'name': 'DISH Network Corporation', 'exchange': 'NASDAQ', 'sector': 'Communication Services', 'industry': 'Satellite'},
        {'symbol': 'SIRI', 'name': 'Sirius XM Holdings Inc.', 'exchange': 'NASDAQ', 'sector': 'Communication Services', 'industry': 'Radio'},
        {'symbol': 'LUMN', 'name': 'Lumen Technologies Inc.', 'exchange': 'NYSE', 'sector': 'Communication Services', 'industry': 'Telecommunications'},
        {'symbol': 'CTL', 'name': 'CenturyLink Inc.', 'exchange': 'NYSE', 'sector': 'Communication Services', 'industry': 'Telecommunications'},
        {'symbol': 'FTR', 'name': 'Frontier Communications Parent Inc.', 'exchange': 'NASDAQ', 'sector': 'Communication Services', 'industry': 'Telecommunications'},
        {'symbol': 'TWTR', 'name': 'Twitter Inc.', 'exchange': 'NYSE', 'sector': 'Communication Services', 'industry': 'Social Media'},
        {'symbol': 'SNAP', 'name': 'Snap Inc.', 'exchange': 'NYSE', 'sector': 'Communication Services', 'industry': 'Social Media'},
        {'symbol': 'PINS', 'name': 'Pinterest Inc.', 'exchange': 'NYSE', 'sector': 'Communication Services', 'industry': 'Social Media'},
        {'symbol': 'SPOT', 'name': 'Spotify Technology S.A.', 'exchange': 'NYSE', 'sector': 'Communication Services', 'industry': 'Music Streaming'},
        {'symbol': 'RBLX', 'name': 'Roblox Corporation', 'exchange': 'NYSE', 'sector': 'Communication Services', 'industry': 'Gaming'},
        
        # Materials
        {'symbol': 'LIN', 'name': 'Linde plc', 'exchange': 'NYSE', 'sector': 'Materials', 'industry': 'Industrial Gases'},
        {'symbol': 'APD', 'name': 'Air Products and Chemicals Inc.', 'exchange': 'NYSE', 'sector': 'Materials', 'industry': 'Industrial Gases'},
        {'symbol': 'SHW', 'name': 'Sherwin-Williams Company', 'exchange': 'NYSE', 'sector': 'Materials', 'industry': 'Paints & Coatings'},
        {'symbol': 'ECL', 'name': 'Ecolab Inc.', 'exchange': 'NYSE', 'sector': 'Materials', 'industry': 'Specialty Chemicals'},
        {'symbol': 'DD', 'name': 'DuPont de Nemours Inc.', 'exchange': 'NYSE', 'sector': 'Materials', 'industry': 'Specialty Chemicals'},
        {'symbol': 'DOW', 'name': 'Dow Inc.', 'exchange': 'NYSE', 'sector': 'Materials', 'industry': 'Commodity Chemicals'},
        {'symbol': 'PPG', 'name': 'PPG Industries Inc.', 'exchange': 'NYSE', 'sector': 'Materials', 'industry': 'Paints & Coatings'},
        {'symbol': 'NEM', 'name': 'Newmont Corporation', 'exchange': 'NYSE', 'sector': 'Materials', 'industry': 'Gold Mining'},
        {'symbol': 'FCX', 'name': 'Freeport-McMoRan Inc.', 'exchange': 'NYSE', 'sector': 'Materials', 'industry': 'Copper Mining'},
        {'symbol': 'NUE', 'name': 'Nucor Corporation', 'exchange': 'NYSE', 'sector': 'Materials', 'industry': 'Steel'},
        {'symbol': 'STLD', 'name': 'Steel Dynamics Inc.', 'exchange': 'NASDAQ', 'sector': 'Materials', 'industry': 'Steel'},
        {'symbol': 'X', 'name': 'United States Steel Corporation', 'exchange': 'NYSE', 'sector': 'Materials', 'industry': 'Steel'},
        {'symbol': 'CLF', 'name': 'Cleveland-Cliffs Inc.', 'exchange': 'NYSE', 'sector': 'Materials', 'industry': 'Steel'},
        {'symbol': 'AA', 'name': 'Alcoa Corporation', 'exchange': 'NYSE', 'sector': 'Materials', 'industry': 'Aluminum'},
        {'symbol': 'IFF', 'name': 'International Flavors & Fragrances Inc.', 'exchange': 'NYSE', 'sector': 'Materials', 'industry': 'Specialty Chemicals'},
        
        # Additional Major Companies
        {'symbol': 'AMZN', 'name': 'Amazon.com Inc.', 'exchange': 'NASDAQ', 'sector': 'Consumer Discretionary', 'industry': 'E-commerce'},
        {'symbol': 'GOOG', 'name': 'Alphabet Inc. Class C', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Internet'},
        {'symbol': 'BRK.A', 'name': 'Berkshire Hathaway Inc. Class A', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Conglomerate'},
        {'symbol': 'BRK.B', 'name': 'Berkshire Hathaway Inc. Class B', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Conglomerate'},
        {'symbol': 'LLY', 'name': 'Eli Lilly and Company', 'exchange': 'NYSE', 'sector': 'Healthcare', 'industry': 'Pharmaceuticals'},
        {'symbol': 'AVGO', 'name': 'Broadcom Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Semiconductors'},
        {'symbol': 'PEP', 'name': 'PepsiCo Inc.', 'exchange': 'NASDAQ', 'sector': 'Consumer Staples', 'industry': 'Beverages'},
        {'symbol': 'COST', 'name': 'Costco Wholesale Corporation', 'exchange': 'NASDAQ', 'sector': 'Consumer Staples', 'industry': 'Retail'},
        {'symbol': 'TMO', 'name': 'Thermo Fisher Scientific Inc.', 'exchange': 'NYSE', 'sector': 'Healthcare', 'industry': 'Life Sciences'},
        {'symbol': 'ABT', 'name': 'Abbott Laboratories', 'exchange': 'NYSE', 'sector': 'Healthcare', 'industry': 'Medical Devices'},
        {'symbol': 'DHR', 'name': 'Danaher Corporation', 'exchange': 'NYSE', 'sector': 'Healthcare', 'industry': 'Life Sciences'},
        {'symbol': 'ACN', 'name': 'Accenture plc', 'exchange': 'NYSE', 'sector': 'Technology', 'industry': 'IT Services'},
        {'symbol': 'VZ', 'name': 'Verizon Communications Inc.', 'exchange': 'NYSE', 'sector': 'Communication Services', 'industry': 'Telecommunications'},
        {'symbol': 'ADBE', 'name': 'Adobe Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'CRM', 'name': 'Salesforce Inc.', 'exchange': 'NYSE', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'TXN', 'name': 'Texas Instruments Incorporated', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Semiconductors'},
        {'symbol': 'QCOM', 'name': 'QUALCOMM Incorporated', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Semiconductors'},
        {'symbol': 'INTC', 'name': 'Intel Corporation', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Semiconductors'},
        {'symbol': 'AMD', 'name': 'Advanced Micro Devices Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Semiconductors'},
        {'symbol': 'CSCO', 'name': 'Cisco Systems Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Networking'},
        {'symbol': 'IBM', 'name': 'International Business Machines Corporation', 'exchange': 'NYSE', 'sector': 'Technology', 'industry': 'IT Services'},
        {'symbol': 'ORCL', 'name': 'Oracle Corporation', 'exchange': 'NYSE', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'NOW', 'name': 'ServiceNow Inc.', 'exchange': 'NYSE', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'SNOW', 'name': 'Snowflake Inc.', 'exchange': 'NYSE', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'ZM', 'name': 'Zoom Video Communications Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'DOCU', 'name': 'DocuSign Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'CRWD', 'name': 'CrowdStrike Holdings Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Cybersecurity'},
        {'symbol': 'OKTA', 'name': 'Okta Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Cybersecurity'},
        {'symbol': 'PANW', 'name': 'Palo Alto Networks Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Cybersecurity'},
        {'symbol': 'NET', 'name': 'Cloudflare Inc.', 'exchange': 'NYSE', 'sector': 'Technology', 'industry': 'Internet Infrastructure'},
        {'symbol': 'DDOG', 'name': 'Datadog Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'MDB', 'name': 'MongoDB Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'TEAM', 'name': 'Atlassian Corporation', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'WDAY', 'name': 'Workday Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'INTU', 'name': 'Intuit Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'ADSK', 'name': 'Autodesk Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'ANSS', 'name': 'ANSYS Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'CDNS', 'name': 'Cadence Design Systems Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'SNPS', 'name': 'Synopsys Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'KLAC', 'name': 'KLA Corporation', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Semiconductor Equipment'},
        {'symbol': 'LRCX', 'name': 'Lam Research Corporation', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Semiconductor Equipment'},
        {'symbol': 'AMAT', 'name': 'Applied Materials Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Semiconductor Equipment'},
        {'symbol': 'MU', 'name': 'Micron Technology Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Memory'},
        {'symbol': 'WDC', 'name': 'Western Digital Corporation', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Storage'},
        {'symbol': 'STX', 'name': 'Seagate Technology Holdings plc', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Storage'},
        {'symbol': 'NTAP', 'name': 'NetApp Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Storage'},
        {'symbol': 'VMW', 'name': 'VMware Inc.', 'exchange': 'NYSE', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'RHT', 'name': 'Red Hat Inc.', 'exchange': 'NYSE', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'SPLK', 'name': 'Splunk Inc.', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'ELK', 'name': 'Elastic N.V.', 'exchange': 'NYSE', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'ESTC', 'name': 'Elasticsearch Inc.', 'exchange': 'NYSE', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'MSTR', 'name': 'MicroStrategy Incorporated', 'exchange': 'NASDAQ', 'sector': 'Technology', 'industry': 'Software'},
        {'symbol': 'SQ', 'name': 'Block Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Payment Processing'},
        {'symbol': 'PYPL', 'name': 'PayPal Holdings Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Payment Processing'},
        {'symbol': 'COIN', 'name': 'Coinbase Global Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Cryptocurrency'},
        {'symbol': 'SOFI', 'name': 'SoFi Technologies Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Fintech'},
        {'symbol': 'UPST', 'name': 'Upstart Holdings Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Fintech'},
        {'symbol': 'HOOD', 'name': 'Robinhood Markets Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Trading'},
        {'symbol': 'SCHW', 'name': 'Charles Schwab Corporation', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Investment Services'},
        {'symbol': 'BLK', 'name': 'BlackRock Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Asset Management'},
        {'symbol': 'BX', 'name': 'Blackstone Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Private Equity'},
        {'symbol': 'KKR', 'name': 'KKR & Co. Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Private Equity'},
        {'symbol': 'APO', 'name': 'Apollo Global Management Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Private Equity'},
        {'symbol': 'CG', 'name': 'The Carlyle Group Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Private Equity'},
        {'symbol': 'ARES', 'name': 'Ares Management Corporation', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Asset Management'},
        {'symbol': 'BAM', 'name': 'Brookfield Asset Management Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Asset Management'},
        {'symbol': 'BEN', 'name': 'Franklin Resources Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Asset Management'},
        {'symbol': 'IVZ', 'name': 'Invesco Ltd.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Asset Management'},
        {'symbol': 'TROW', 'name': 'T. Rowe Price Group Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Asset Management'},
        {'symbol': 'WU', 'name': 'Western Union Company', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Payment Processing'},
        {'symbol': 'FIS', 'name': 'Fidelity National Information Services Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Payment Processing'},
        {'symbol': 'FISV', 'name': 'Fiserv Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Payment Processing'},
        {'symbol': 'GPN', 'name': 'Global Payments Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Payment Processing'},
        {'symbol': 'JKHY', 'name': 'Jack Henry & Associates Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Payment Processing'},
        {'symbol': 'MCO', 'name': 'Moody\'s Corporation', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Credit Rating'},
        {'symbol': 'SPGI', 'name': 'S&P Global Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Credit Rating'},
        {'symbol': 'MSCI', 'name': 'MSCI Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Financial Data'},
        {'symbol': 'NDAQ', 'name': 'Nasdaq Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Exchange'},
        {'symbol': 'CME', 'name': 'CME Group Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Exchange'},
        {'symbol': 'ICE', 'name': 'Intercontinental Exchange Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Exchange'},
        {'symbol': 'CBOE', 'name': 'Cboe Global Markets Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Exchange'},
        {'symbol': 'MKTX', 'name': 'MarketAxess Holdings Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Trading'},
        {'symbol': 'LPLA', 'name': 'LPL Financial Holdings Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Investment Services'},
        {'symbol': 'AMG', 'name': 'Affiliated Managers Group Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Asset Management'},
        {'symbol': 'SEIC', 'name': 'SEI Investments Company', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Asset Management'},
        {'symbol': 'STT', 'name': 'State Street Corporation', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'NTRS', 'name': 'Northern Trust Corporation', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'PNC', 'name': 'PNC Financial Services Group Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'USB', 'name': 'U.S. Bancorp', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'TFC', 'name': 'Truist Financial Corporation', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'CFG', 'name': 'Citizens Financial Group Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'HBAN', 'name': 'Huntington Bancshares Incorporated', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'RF', 'name': 'Regions Financial Corporation', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'FITB', 'name': 'Fifth Third Bancorp', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'KEY', 'name': 'KeyCorp', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'ZION', 'name': 'Zions Bancorporation N.A.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'CMA', 'name': 'Comerica Incorporated', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'SIVB', 'name': 'SVB Financial Group', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'WAL', 'name': 'Western Alliance Bancorporation', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'PBCT', 'name': 'People\'s United Financial Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'CFR', 'name': 'Cullen/Frost Bankers Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'BOKF', 'name': 'BOK Financial Corporation', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'ASB', 'name': 'Associated Banc-Corp', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'SNV', 'name': 'Synovus Financial Corp.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'FNB', 'name': 'F.N.B. Corporation', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'PNFP', 'name': 'Pinnacle Financial Partners Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'WBS', 'name': 'Webster Financial Corporation', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'HOMB', 'name': 'Home BancShares Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'CBSH', 'name': 'Commerce Bancshares Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'UBSI', 'name': 'United Bankshares Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'FFIN', 'name': 'First Financial Bankshares Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'BKU', 'name': 'BankUnited Inc.', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'TCBI', 'name': 'Texas Capital Bancshares Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'COLB', 'name': 'Columbia Banking System Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'FULT', 'name': 'Fulton Financial Corporation', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'CATY', 'name': 'Cathay General Bancorp', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'PPBI', 'name': 'Pacific Premier Bancorp Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'SASR', 'name': 'Sandy Spring Bancorp Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'WSFS', 'name': 'WSFS Financial Corporation', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'FIBK', 'name': 'First Interstate BancSystem Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'BANR', 'name': 'Banner Corporation', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'FFBC', 'name': 'First Financial Bancorp', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'ONB', 'name': 'Old National Bancorp', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'HOPE', 'name': 'Hope Bancorp Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'FHB', 'name': 'First Hawaiian Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'BOH', 'name': 'Bank of Hawaii Corporation', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'WAFD', 'name': 'Washington Federal Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'SFNC', 'name': 'Simmons First National Corporation', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'BANF', 'name': 'BancFirst Corporation', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'CASH', 'name': 'Meta Financial Group Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'FCF', 'name': 'First Commonwealth Financial Corporation', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'BXS', 'name': 'BancorpSouth Bank', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'BUSE', 'name': 'First Busey Corporation', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'FBNC', 'name': 'First Bancorp', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'BANR', 'name': 'Banner Corporation', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'FFBC', 'name': 'First Financial Bancorp', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'ONB', 'name': 'Old National Bancorp', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'HOPE', 'name': 'Hope Bancorp Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'FHB', 'name': 'First Hawaiian Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'BOH', 'name': 'Bank of Hawaii Corporation', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'WAFD', 'name': 'Washington Federal Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'SFNC', 'name': 'Simmons First National Corporation', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'BANF', 'name': 'BancFirst Corporation', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'CASH', 'name': 'Meta Financial Group Inc.', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'FCF', 'name': 'First Commonwealth Financial Corporation', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'BXS', 'name': 'BancorpSouth Bank', 'exchange': 'NYSE', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'BUSE', 'name': 'First Busey Corporation', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
        {'symbol': 'FBNC', 'name': 'First Bancorp', 'exchange': 'NASDAQ', 'sector': 'Financials', 'industry': 'Banking'},
    ]

def get_popular_tickers():
    """Get a curated list of the most popular tickers."""
    return [
        'AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META', 'NVDA', 'TSLA', 'NFLX', 'ADBE', 'CRM',
        'JPM', 'BAC', 'WFC', 'GS', 'V', 'MA', 'PYPL', 'JNJ', 'PFE', 'UNH',
        'ABBV', 'MRK', 'TMO', 'ABT', 'PG', 'KO', 'PEP', 'WMT', 'HD', 'MCD',
        'NKE', 'DIS', 'SBUX', 'BA', 'CAT', 'GE', 'HON', 'UPS', 'FDX', 'XOM',
        'CVX', 'COP', 'NEE', 'SO', 'DUK', 'AMT', 'PLD', 'CCI', 'VZ', 'T'
    ]
